import assert from "node:assert/strict";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import test from "node:test";
import { getStatus, initializeProject } from "../src/runtime/index.js";
import { ProjectBrainStore } from "../src/project-brain/store.js";
import { applyMigrationUpdate, planMigrationUpdate, readMigrationJournal } from "../src/lifecycle/migration.js";
import { planNormalUpdate, type ReleaseDescriptor } from "../src/lifecycle/update.js";
import { migrationApplyOptions, migrationArtifact, migrationRelease } from "./migration-runtime-fixture.js";

function applyOptions(overrides: Record<string, unknown> = {}) { return migrationApplyOptions(overrides) as Parameters<typeof applyMigrationUpdate>[2]; }
async function withProject(run: (path: string) => Promise<void>): Promise<void> { const path=await mkdtemp(join(tmpdir(),"pbf-migration-")); try { await initializeProject(path,{authorized:true}); await run(path); } finally { await rm(path,{recursive:true,force:true}); } }
async function projectKnowledge(path: string): Promise<Record<string, Buffer>> { const result:Record<string,Buffer>={}; for(const file of ["project.md","goals.md","decisions.md","knowledge.md"]) result[file]=await readFile(resolve(path,".project-brain",file)); return result; }

test("schema-changing release cannot use normal update path and produces artifact-bound migration plan", async()=>{await withProject(async(path)=>{await assert.rejects(()=>planNormalUpdate(path,[migrationRelease]),/schema migration/i); const plan=await planMigrationUpdate(path,migrationRelease); assert.equal(plan.compatibility,"compatible_with_migration"); assert.equal(plan.migrationRequired,true); assert.equal(plan.checkpointRequired,true); assert.equal(plan.authorizationRequired,true); assert.equal(plan.migration.id,"pb-schema-1-to-2"); assert.equal(plan.migration.replaySafe,false); assert.equal(plan.sourceId,"official-local-test-source"); assert.equal(plan.artifactId,"runtime-node-cli-migration"); assert.equal(plan.artifactSha256,migrationRelease.artifact.sha256);});});

test("unsupported or incomplete migration path fails closed",async()=>{await withProject(async(path)=>{const unsupported:ReleaseDescriptor={...migrationRelease,version:"0.0.2-development.1",projectBrainSchema:3}; await assert.rejects(()=>planMigrationUpdate(path,unsupported),/No unambiguous supported migration path/i); assert.equal((await new ProjectBrainStore(path).readMetadata()).projectBrain.schemaVersion,1);});});

test("successful migration preserves project knowledge and adjacent metadata while activating only after validation",async()=>{await withProject(async(path)=>{const before=await projectKnowledge(path); const metadataPath=resolve(path,".project-brain","metadata.json"); const initial=JSON.parse(await readFile(metadataPath,"utf8")) as Record<string,unknown>; await writeFile(metadataPath,`${JSON.stringify({...initial,projectOwnedExtension:{keep:"yes"},lifecycle:{existingField:"preserve-me",migrationHistory:["prior-migration"]}},null,2)}\n`,`utf8`); const plan=await planMigrationUpdate(path,migrationRelease); let sawTargetBeforeValidation=false; await applyMigrationUpdate(path,plan,applyOptions({validate:async()=>{const metadata=await new ProjectBrainStore(path).readMetadata(); sawTargetBeforeValidation=metadata.framework.version===plan.targetVersion; assert.equal(metadata.projectBrain.schemaVersion,2);}})); assert.equal(sawTargetBeforeValidation,false); const afterMetadata=await new ProjectBrainStore(path).readMetadata() as unknown as {framework:{version:string;channel:string};projectBrain:{schemaVersion:number};projectOwnedExtension?:{keep?:string};lifecycle?:{existingField?:string;migrationHistory?:string[]}}; assert.equal(afterMetadata.framework.version,plan.targetVersion); assert.equal(afterMetadata.projectBrain.schemaVersion,2); assert.equal(afterMetadata.projectOwnedExtension?.keep,"yes"); assert.equal(afterMetadata.lifecycle?.existingField,"preserve-me"); assert.deepEqual(afterMetadata.lifecycle?.migrationHistory,["prior-migration","pb-schema-1-to-2"]); for(const [file,bytes] of Object.entries(before)) assert.deepEqual(await readFile(resolve(path,".project-brain",file)),bytes); const journal=await readMigrationJournal(path); assert.equal(journal?.state,"complete"); assert.equal(journal?.stepState,"completed");});});

test("tampered migration artifact fails before checkpoint or schema mutation",async()=>{await withProject(async(path)=>{const plan=await planMigrationUpdate(path,migrationRelease); const tampered=resolve(path,"tampered.artifact"); await writeFile(tampered,"tampered migration bytes\n","utf8"); await assert.rejects(()=>applyMigrationUpdate(path,plan,applyOptions({artifact:migrationArtifact({path:tampered})})),/integrity verification failed/i); const metadata=await new ProjectBrainStore(path).readMetadata(); assert.equal(metadata.framework.version,plan.sourceVersion); assert.equal(metadata.projectBrain.schemaVersion,1); assert.equal(await readMigrationJournal(path),null);});});

test("migration failure uses staged rollback and restores schema and active version",async()=>{await withProject(async(path)=>{const before=await projectKnowledge(path); const plan=await planMigrationUpdate(path,migrationRelease); await assert.rejects(()=>applyMigrationUpdate(path,plan,applyOptions({failAfterMutation:true})),/simulated migration failure/); const metadata=await new ProjectBrainStore(path).readMetadata(); assert.equal(metadata.framework.version,plan.sourceVersion); assert.equal(metadata.projectBrain.schemaVersion,1); for(const [file,bytes] of Object.entries(before)) assert.deepEqual(await readFile(resolve(path,".project-brain",file)),bytes); assert.equal((await readMigrationJournal(path))?.state,"failed");});});

test("automatic rollback failure leaves current state intact and narrows to recovery-required",async()=>{await withProject(async(path)=>{const before=await projectKnowledge(path); const plan=await planMigrationUpdate(path,migrationRelease); const checkpointMetadata=resolve(path,`.project-brain.checkpoint-${plan.operationId}`,"metadata.json"); await assert.rejects(()=>applyMigrationUpdate(path,plan,applyOptions({failAfterMutation:true,beforeAutomaticRollback:async()=>{await writeFile(checkpointMetadata,"{broken-checkpoint","utf8");}})),/simulated migration failure/); const current=await new ProjectBrainStore(path).readMetadata(); assert.equal(current.framework.version,plan.sourceVersion); assert.equal(current.projectBrain.schemaVersion,2); for(const [file,bytes] of Object.entries(before)) assert.deepEqual(await readFile(resolve(path,".project-brain",file)),bytes); assert.equal((await readMigrationJournal(path))?.state,"recovery-required"); assert.equal((await getStatus(path)).lifecycle,"recovery-required");});});

test("interrupted in-progress migration is detected and cannot be blindly replayed",async()=>{await withProject(async(path)=>{const plan=await planMigrationUpdate(path,migrationRelease); await applyMigrationUpdate(path,plan,applyOptions({interruptAfterMutation:true})); const journal=await readMigrationJournal(path); assert.equal(journal?.state,"applying"); assert.equal(journal?.stepState,"in-progress"); await assert.rejects(()=>applyMigrationUpdate(path,plan,applyOptions()),/Interrupted or ambiguous migration requires recovery/i);});});

test("migration requires explicit authorization even for a verified artifact",async()=>{await withProject(async(path)=>{const plan=await planMigrationUpdate(path,migrationRelease); await assert.rejects(()=>applyMigrationUpdate(path,plan,applyOptions({authorized:false})),/explicit authorization/i);});});
